### ISSUE TITLE
[Feature] Add Button to start the game

### ISSUE THREAD

**Issue by Nitesh-thapliyal** [Bauddhik-Geeks/Snake-Game#1]

**Comment by aanchal-fatwani** [comment]
Hi, I would like to work on this issue. Please assign the same.

**Comment by adityamangal1** [comment]
Hey @aanchal-fatwani if you haven't yet, Can you please join the organization and discord server first so that your contribution is counted as hacktoberfest accepted.😊. @Nitesh-thapliyal will assign you soon this issue
Organization link👉 https://github.com/Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks
Discord server link 👉 https://join.bauddhikgeeks.tech
