### ISSUE TITLE
[Feature] Show high score of the user

### ISSUE THREAD

**Issue by Nitesh-thapliyal** [Bauddhik-Geeks/Snake-Game#2]

**Comment by TDP17** [comment]
Hi, I would like to work on this as my first issue. Please assign me to the same 

(I feel localstorage would suffice for this)

**Comment by adityamangal1** [comment]
Go ahead @TDP17, @Nitesh-thapliyal will assign you soon. Meanwhile, make sure to join the organization and discord server first so that your contribution is counted as hacktoberfest accepted.😊

Organization link👉 https://github.com/Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks
Discord server link 👉 https://join.bauddhikgeeks.tech
